### ISSUE TITLE
Issue when rendering page

### ISSUE THREAD

**Issue by Cardosaum** [craft-ex/phoenix_live_view_collection#11]
Currently the website displays as follows: ![image](https://github.com/leandrocp/live_view_demos/assets/45436839/1946ca8c-c7c6-4dff-930e-0842745e8228)

Not sure where exactly it's breaking... I'd expect fetching the twitter links is the culprit?

**Comment by leandrocp** [comment]
Hi @Cardosaum, please review this comment and see if that helps https://github.com/leandrocp/live_view_demos/issues/9#issuecomment-1444159252

**Comment by Cardosaum** [comment]
Oh, it does indeed!
Thanks 😊
