### ISSUE TITLE
Twitter entries don’t load with Firefox’s Enhanced Tracking Protection enabled

### ISSUE THREAD

**Issue by Diti** [craft-ex/phoenix_live_view_collection#5]
Firefox may be configured to [block cross-site tracking cookies](https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop) (for example in Strict blocking mode), in which case no tweet will load on [liveviewdemos.org](https://liveviewdemos.com).

> `The resource at “https://platform.twitter.com/widgets.js” was blocked because content blocking is enabled.`

As far as I know, it is not possible to use Twitter embeds without the trackers.

I think a more useful error message should be displayed to the end-user when this resource fails to load, instead of having the application hang forever on trying to load the embeds.

**Comment by leandrocp** [comment]
Hi @Diti good catch, thanks!
