### ISSUE TITLE
Hi! I think the app is not loading at the moment?

### ISSUE THREAD

**Issue by pdgonzalez872** [craft-ex/phoenix_live_view_collection#9]
@leandrocp thanks for the repo? I wanted to reach out about prod not working? Maybe it was just me: 
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/8906358/221254841-c32abb73-8dd7-4784-b2ae-52daa517b3cb.png">

https://liveviewdemos.com/?search=&page=1

Maybe I'm missing something 😂 

Thanks again for the repo, have a great weekend!

**Comment by pdgonzalez872** [comment]
It's been going on for a couple minutes at the moment

**Comment by leandrocp** [comment]
Hi @pdgonzalez872 those cards are loaded by the twitter js api https://platform.twitter.com/widgets.js which may get blocked by ad blockers, VPNs, or depending on your network config it may be blocked as well. Please inspect the Network or Console tab on your browser for loading errors and/or try to review your env to allow that js request. Thanks!

**Comment by pdgonzalez872** [comment]
Indeed! 
<img width="1604" alt="image" src="https://user-images.githubusercontent.com/8906358/221256191-e5737041-190e-4623-b074-0d79880ba13b.png">


Thanks @leandrocp ! Closing this!

**Comment by leandrocp** [comment]
Btw I'm working to improve how the data is loaded, currently it's more a hack than something really stable so it's not rare to get the app down 😅

**Comment by pdgonzalez872** [comment]
haha all good, love the work regardless ❤️
